# filekinds:
#   normal:
#     foreground: White
#   directory:
#     foreground: Blue
#   symlink:
#     foreground: Cyan
#   executable:
#     foreground: Green
# perms:
#   user_read:
#     foreground: Yellow
#     is_bold: true
#   user_write:
#     foreground: Red
#     is_bold: true
#   user_execute_file:
#     foreground: Green
#     is_bold: true
#   user_execute_other:
#     foreground: Green
#     is_bold: true
#   group_read:
#     foreground: Yellow
#   group_write:
#     foreground: Red
#   group_execute:
#     foreground: Green
#   other_read:
#     foreground: Yellow
#   other_write:
#     foreground: Red
#   other_execute:
#     foreground: Green
filenames:
  # Just change the icon glyph
  Cargo.toml: {icon: {glyph: ü¶Ä}}
  Cargo.lock: {icon: {glyph: ü¶Ä}}
extensions:
  # Change the filename color and icon
  # NOTE: not all unicode glyphs support color changes
  rs: {filename: {foreground: Red}, icon: {glyph: ü¶Ä}}
  typ: {filename: {foreground: White}, icon: {glyph: ÔÖú}}
  j2: {filename: {foreground: Yellow}, icon: {glyph: ÓòÜ, style: {foreground: Yellow}}}
  jinja2: {filename: {foreground: Yellow}, icon: {glyph: ÓòÜ, style: {foreground: Yellow}}}
  # Change the icon glyph and color
  nix: {icon: {glyph: ‚ùÑ, style: {foreground: White}}}
